### ISSUE TITLE
Image Quality

### ISSUE THREAD

**Issue by Pfuenzle** [Witness-senpai/fakku-downloader#1]
First of, thanks for this project, its working fine.
But the picture quality is not that great. I tried to improve it by playing with the resolution parameters, but it didnt seem to change anything. Do you think it would be possible to improve the resolution by any means?
For example by zooming in and taking 3 screenshots from each a third of the page?

Thanks

**Comment by Witness-senpai** [comment]
Thanks for your question. Have you tried running the script with -t option? This parameter means timeout between open the page and it downloading. You can increase this parameter to 2 or more (by default it equals 1 sec).
That is, you can run script like this: **python main.py -t=2**

**Comment by Pfuenzle** [comment]
Yes, that really improved the resolution. I thought it was because of the zoom factor, but now its fine. Thanks 👍
