### ISSUE TITLE
All downloads timing out

### ISSUE THREAD

**Issue by yepsame** [Witness-senpai/fakku-downloader#16]
The last time I used it (around a month or so ago) it worked fine, and with no settings changes at all I'm now getting timed out whenever I attempt to download. I've tried changing my timeout, but even with an extremely long timeout I'm getting the same issue.

**Comment by yepsame** [comment]
update: it seems like it might have been captcha related? i did a fresh install, same settings, and while logging in, fakku had me complete ~10 captchas and the download started out perfectly fine.

**Comment by nietbestaand013** [comment]
Hi @yepsame can you send me your cookies.pickle? I have the same issue and a clean install didn't work for me

**Comment by Witness-senpai** [comment]
As I know, cookies have their own lifetime. I think your cookie has expired and you couldn't connect to Fakku using it.
