### ISSUE TITLE
cant even start the python

### ISSUE THREAD

**Issue by idrfcare** [Witness-senpai/fakku-downloader#18]
can you please help me what happened here? i can't even enter python

[https://files.catbox.moe/xszaaj.PNG](url)

**Comment by idrfcare** [comment]
ok, i'm just stupid, wrong installation of python, but i get this this time

Traceback (most recent call last):
  File "C:\Users\arifr\OneDrive\Desktop\fakku-downloader-master\main.py", line 4, in <module>
    from downloader import (
  File "C:\Users\arifr\OneDrive\Desktop\fakku-downloader-master\downloader.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

**Comment by Witness-senpai** [comment]
Please, repeat installation steps from README:

1) Download or clone this repository
2) Download [ChromeDriver](https://chromedriver.chromium.org/downloads) the same version as you Chrome Browser and move it in root folder.
(Rename it to **chromedriver.exe**)
3) Create **urls.txt** file in root folder and write into that urls of manga one by line
4) Install all requirements for script via run **install.bat** (for Windows) or run <code>pip install -r requirements.txt</code>
5) Open root folder in command line and run the command <code>python main.py</code>
