### ISSUE TITLE
Passthrough not supported, GL disabled?

### ISSUE THREAD

**Issue by idrfcare** [Witness-senpai/fakku-downloader#22]
hi, anyone knows why this happened?
![Capture12345](https://user-images.githubusercontent.com/86952371/128418273-cbd9276c-e8df-436a-9a4d-6ce42fa63527.PNG)

**Comment by Xitherun** [comment]
Edit line 190 of downloader.py and change this:

`self.browser.find_element_by_class_name('js-submit').click()`

To this:

`self.browser.find_element_by_class_name('js-submit-login').click()`

**Comment by HeartFire01** [comment]
> Edit line 190 of downloader.py and change this:
> 
> `self.browser.find_element_by_class_name('js-submit').click()`
> 
> To this:
> 
> `self.browser.find_element_by_class_name('js-submit-login').click()`

Stil not working after change that line...
![image](https://user-images.githubusercontent.com/64661805/129861845-f14de084-0781-44cb-86b1-df80532017d4.png)
![image](https://user-images.githubusercontent.com/64661805/129861877-5b21d265-2362-40e0-9994-7f392a367f6c.png)

**Comment by idrfcare** [comment]
i can't use chrome 94, i need to use chrome 91, how to downgrade the chrome version?

**Comment by idrfcare** [comment]
idk what happen but it suddenly works
