### ISSUE TITLE
Do I need an Unlimited Account

### ISSUE THREAD

**Issue by TeedGa** [Witness-senpai/fakku-downloader#32]
Hello,

I'm trying to download this one, but I keep getting this error. So I was wondering if I need an unlimited account to use the downloader.

I've already tried multiple times to delete the cookies.pickle file and login again. No dice.
![image](https://user-images.githubusercontent.com/93822152/140607101-901ef320-81a4-424e-9d1a-cd26478e5c01.png)

**Comment by Witness-senpai** [comment]
Of course, script can download only books that you can read from browser using you acc
