### ISSUE TITLE
Syntax error (using Python 2.7.13 version)

### ISSUE THREAD

**Issue by HeartFire01** [Witness-senpai/fakku-downloader#4]
I have a problem when i run _python main.py_ in cmd, it shows 

![image](https://user-images.githubusercontent.com/64661805/107697959-74a23f00-6ce6-11eb-8250-1c4fb7a88d61.png)

**Comment by HeartFire01** [comment]
I have a problem when i run python main.py in cmd, it shows


image

**Comment by Witness-senpai** [comment]
Please use python 3.* for running this script. Python 2 is not supported.

**Comment by HeartFire01** [comment]
@Witness-senpai When i try using python 3.9 it shows :
