### ISSUE TITLE
@Witness-senpai When i try using python 3.9 it shows :

### ISSUE THREAD

**Issue by HeartFire01** [Witness-senpai/fakku-downloader#5]
@Witness-senpai When i try using python 3.9 it shows : 
![image](https://user-images.githubusercontent.com/64661805/107796268-3c553c00-6d8c-11eb-9db2-ef7ea2479ae5.png)

_Originally posted by @HeartFire01 in https://github.com/Witness-senpai/fakku-downloader/issues/4#issuecomment-778306274_

**Comment by Witness-senpai** [comment]
Fast temporary solution -- just create an empty 'done.txt' file. This should work.
