### ISSUE TITLE
Browser doesn't open

### ISSUE THREAD

**Issue by Tibsi** [Witness-senpai/fakku-downloader#51]
![image](https://github.com/Witness-senpai/fakku-downloader/assets/45721845/0149cecd-5dda-478a-8f96-0f650d591197)

Whenever I try to start it, I get those and no browser window opens. 

I have tried both the current x32 and x64 versions of chromedriver with python 3.12

**Comment by Tibsi** [comment]
seems I already had newer versions of selenium installed that isn't compatible anymore.
but I got it solved

**Comment by mslmn** [comment]
> seems I already had newer versions of selenium installed that isn't compatible anymore. but I got it solved

@Tibsi  how did you manage to get it working?

**Comment by Tibsi** [comment]
> > seems I already had newer versions of selenium installed that isn't compatible anymore. but I got it solved
> 
> @Tibsi how did you manage to get it working?

I just went with the newest chromedriver and switched the packages to selenium 4.9.0, beautifulsoup4 4.8.2 and tqdm 4.64.1.
thats seemed to work with chrome 117 that I head at the time. 
That being said, it's really slow and inefficient so I made my own slightly modified version of this fork:
https://github.com/beerpiss/fakk-u-downloader

There are no instructions on it yet, but it's basically the same thing. So the "How to Launch" stays the same. Except that you have to create a cookies.txt after logging into the Fakku website with your Chrome Addon of Choice (I use this one https://chrome.google.com/webstore/detail/get-cookiestxt-clean/ahmnmhfbokciafffnknlekllgcnafnie) and put it in the program folder.
